### ISSUE TITLE
[#111] [Testing] e2e Testing Sprint 6

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#111]
Implement e2e testing for the users stories that are completed
- [x] #29 Study Hour Estimator
- [ ] #102 Camera-based Event Creation [CLIENT SIDE FUNCTIONING ONLY]

**Comment by EyalAzimov** [comment]
<img width="1236" alt="Screen Shot 2023-02-15 at 6 05 03 PM" src="https://user-images.githubusercontent.com/78042498/219209838-b6fa62e3-bc1a-4b40-94e8-898ec336c6ae.png">
