### ISSUE TITLE
Calendar Event Creation [SP-13]

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#13]
As a user, I want to create a calendar entry with a specific tag (appointment/task/event/exam) to populate my schedule.The user will be able to create new calendar events and associate tags to them for better organization of their schedule.
Business Value: XL
Priority: High
Effort: 13

Front end 
- [x] Create layout of event creation
- [x] refer to sp-16,18 19 for tagging and hyperlink

back end
Create event table and its inherited classes
Route to create and update events
appropriate methods for events in ExpressJs

**Comment by guaj** [comment]
Done for front-end
