### ISSUE TITLE
Academic calendar events [SP-15]

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#15]
Description:
As a user, I want Concordia's undergraduate academic dates to be integrated in my calendar so I can keep track of important dates (eg. add/drop, disc, etc).

The user will have Concordia’s undergraduate academic dates integrated in their calendars so they can stay on track with important deadlines.
All dates
Business Value: L
Priority: high
Effort:  3

tasks
frontend:
- [x] display academic events in calendar looking like the image below but using color: E5A712 instead of the purple color
<img width="74" alt="Screen Shot 2022-11-13 at 5 12 05 PM" src="https://user-images.githubusercontent.com/43822671/201547121-43f0bb4f-8db0-46c6-93c8-dfadb72c97e2.png">

backend:
- [x] endpoint to access academic calendar dates

Acceptance Criteria for searching for Academic calendar events [SP-15]
As a user, I can view the orange calendar tile on the calendar display representing important Concordia dates
As a user, I can see a header titled 'Important Academic Events' 
I can view all important Concordia dates and descriptions
I can scroll through the list of important Concordia dates
There is no 'update' or 'delete' button on the important Concordia dates events display
 Acceptance test: APPROVED

**Comment by jacobmathewlopez** [comment]
Backend has been implemented in PR:

https://github.com/guaj/SemesterPlanner-Server/pull/75/files
