### ISSUE TITLE
Hyperlink Creation for Events [SP-18]

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#18]
Description:
As a user, I want to create hyperlinks in appointment notes to quickly access virtual/Zoom meetings.

The user will be able to add hyperlinks to event/appointment notes for better organization. Hyperlinks could be for online/virtual meetings, or possible links to check out during this event/appointment.

Business Value: small
Priority: medium
Effort: 3
- [ ] task

Backend
Attribute for hyperlink? (do research)

**Comment by guaj** [comment]
Done for front-end
