### ISSUE TITLE
Recurring Event Creation [SP-19]

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#19]
As a user, I would like to be able to create recurring appointments so I don't have to add similar appointments manually.The user will be able to create recurring appointments/events to avoid manually creating an event multiple times 
over a certain period.

Every day
Every week *if feasible add custom time lapse
Every Month

be able to delete events. Deleting is for all the following events *if feasible add custom time lapse

Business Value: XL
Priority: High
Effort: 5

task
- [ ] add a disclaimer that the delete event button deletes all recurring event starting on the day of the delete

Back end
- [ ] recurring event function in Calander file (easier done in front end, communicate with front end team)

**Comment by guaj** [comment]
Done for front-end
