### ISSUE TITLE
Study Statistics [SP-27] implementation phase

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#27]
As a user, I want to see my study time statistics to improve my efficiency.

The user will be able to views statistics of their study times and study time breakdowns for any given day, allowing them to plan for improvements in their study times (eg. Compensate missing study times on weekends, shift study focus from one course to another, etc.)

2.c The user will be able to see statistics of study time per course, allowing them to find courses with lower study times and adjust their studying priorities.

Daily, weekly, monthly
<img width="802" alt="Screen Shot 2023-01-18 at 2 03 06 PM" src="https://user-images.githubusercontent.com/43822671/213271178-2e20a7a1-ab14-4e8e-b36a-849fb64a4f3c.png">

Business Value: XL
Priority: medium
Effort: 21

issue #112  was created in order to implement the actual study times for each course

tasks:
frontend:
- [x] prototype how with this look like on the application

backend:
- [ ] analyse how to get even types
- [ ] how can a user save it study time
- [ ] how can a user see how much time he studies 
- [ ] how can a user see the time he should study #29 
- [ ] how can a user plan he study time

**Comment by c0rnkrump3t** [comment]
https://react-charts.tanstack.com/
