### ISSUE TITLE
Study Notes Sharing [SP-31]

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#31]
As a user, I want to be able to share study notes with others to help them with their studying.

The user will be able to share their study notes with other students that are on their friend list and have the same virtual study room access. This can help students that may have missed some lectures or are having difficulty grasping some of the concepts being discussed.
Business Value: M
Priority: low
Effort:8

**Comment by mnashat** [comment]
Duplicate issue. Refer to #50.
