### ISSUE TITLE
overriding MUI css

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#37]
Need to figure out how to override the MUI styles in order to be able to put the  most commonly used css in 1 accessible file for everyone. 
For example the background colour and the buttons

**Comment by guaj** [comment]
See ** #84**
The toggle switch has custom css. To style components refer to syling 
See :  https://mui.com/material-ui/customization/how-to-customize/#2-reusable-component
To get the css class to use, you can refer to the api section of your mui component
