### ISSUE TITLE
Display friend list [SP-53]

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#53]
As a user I want to be able to see the list of friends I have in the app. The purpose of having friends is that I can create a study room and include them in it to share ideas and content about school related work. 
US involved:
#54 add user
#55 delete user

tasks:
- [x] add friend list to nav bar
- [x] create friend list page based on prototype (similar to study group layout: having drawer icons at the bottom)
- [x] create a homepage that displays all current friends (confirm/cancel button)
- [x] create a drawer to searching (search icon)users by email/username
- [x] create a drawer ( icon) to display incoming requests (accept or reject) and pending requests (cancel)

backend:
- [x] endpoint to get user based on email or username (searching purposes)
- [x] endpoint to display all your current friends
- [x] endpoint to  delete a user in the friend list of the connected user
- [x] endpoint to display received friend request
- [x] endpoint to display sent friend request
- [x] endpoint to confirm received friend request (should update your other person friend list)
- [x] endpoint to reject received friend request  (should update your other person friend list)
- [x] endpoint to cancel sent friend request  (should update your other person friend list)

Acceptance Criteria for friend list
As a user, when I want to access my friend's list,
I click on friends list in the nav bar,
I am redirected to the Friends list homepage where I see all my friends
Acceptance test: APPROUVED

Acceptance Criteria for deleting a friend
As a user, when I want to delete a friend,
I click on the 'cross' next to the name I want to remove,
If I change my mind, I can click cancel and the list will revert back to the original list
otherwise,
I click confirm,
I can see the updated list without the name I removed
Acceptance test: APPROUVED

Acceptance Criteria for searching for a friend
As a user, when I want to add a friend,
I click on the search icon on the friends list homepage,
I enter the username or email of the person I am looking for,
I click on the name and a friend request is sent to that person
Acceptance test: APPROUVED

Acceptance Criteria for accepting a friend request
As a user, when I want to accept a friend request,
I click on friends list in the nav bar,
I am redirected to the Friends list homepage,
I click on notification icon,
I see pending friend requests,
I click on the check mark,
the friend request is accepted
Acceptance test: APPROUVED

Acceptance Criteria for cancelling a friend request
As a user, when I want to cancel a friend request sent to another student,
I click on friends list in the nav bar,
I am redirected to the Friends list homepage,
I click on notification icon,
I see pending friend requests,
I click on the cancel request button,
the friend request is cancelled
Acceptance test: APPROUVED

Acceptance Criteria for rejecting a friend request
As a user, when I want to reject a friend request,
I click on friends list in the nav bar,
I am redirected to the Friends list homepage,
I click on notification icon,
I see pending friend requests,
I click on the reject button,
the friend request is rejected
Acceptance test: APPROUVED

**Comment by guaj** [comment]
Made the following changes on the objets 
<img width="194" alt="image" src="https://user-images.githubusercontent.com/60197474/202870304-b0398f10-e3f1-4a16-af58-3d42fcfd907b.png">
There is now a friendRequest object that has the following 
_id (generated by mondoDb)
senderEmail : students who sends the friend requests
receiverEmail : students who receives the friend requests

That way we remove the incoming / sent friends requests attributes in the user schema and we combine them both with this single object
