### ISSUE TITLE
[BUG] - Fix Add Event Dropdown Options Position

### ISSUE THREAD

**Issue by jacobmathewlopez** [based-kwl/SemesterPlanner-client#64]
In the calendar component view, the dropdown menu when adding a new event is positioned at the top left side of the screen. This dropdown should be positioned to the left of the button as this menu reflects the actions of this button
<img width="225" alt="Screen Shot 2022-11-06 at 1 49 41 PM" src="https://user-images.githubusercontent.com/59061034/200189509-6be31567-2804-437f-81a4-94c2bc548a9b.png">

**Comment by guaj** [comment]
Will make events clickable instead. won't resolve
