### ISSUE TITLE
[BUG] colorSelection does not diplay user information from the server

### ISSUE THREAD

**Issue by guaj** [based-kwl/SemesterPlanner-client#83]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/60197474/201551752-378258ab-bce1-40a5-96bf-16cd7d311b7d.png">

this function does not do anything. Get request do not accept a body either. We need to specify which user in the url.

**Comment by guaj** [comment]
refer to issue #8 in your branch name

**Comment by kikkiii21** [comment]
This bug is no longer relevant as we do not use color selector in the application
