### ISSUE TITLE
[BUG] friend list displays current friends in on array index instead of different indexes

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#89]
Initial view both the FE and the DB are displaying the information correctly as the images below show
<img width="515" alt="Screen Shot 2022-11-22 at 12 00 59 PM" src="https://user-images.githubusercontent.com/43822671/203416034-b5f94216-8be8-4369-ae36-4641266a32d8.png">

<img width="553" alt="Screen Shot 2022-11-22 at 3 37 00 PM" src="https://user-images.githubusercontent.com/43822671/203416275-98013091-0987-4c1e-aeca-394af7079ea3.png">

once I click on "CONFIRM CHANGES" the variables that were on separate indexed are put in one index as the images show below
<img width="423" alt="Screen Shot 2022-11-22 at 3 27 45 PM" src="https://user-images.githubusercontent.com/43822671/203416063-96727683-a7f4-48fe-af7a-7f0d136ceb17.png">
<img width="568" alt="Screen Shot 2022-11-22 at 3 28 06 PM" src="https://user-images.githubusercontent.com/43822671/203416108-27580fc5-a82a-4d86-8a89-6880d18938ac.png">

**Comment by mnashat** [comment]
@RamB98 Please note that this bug has been fixed.
